### ISSUE TITLE
LyX layout

### ISSUE THREAD

**Issue by cgranade** [cgogolin/quantum-journal#10]
On the subreddit, user ComradeVVA [suggested](https://www.reddit.com/r/quantumjournal/comments/53obp9/two_small_suggestions_regarding_format_and/?st=itcjn5d7&sh=611fbc82) creating a layout for using LyX with `{quantumarticle}`. There seems to be a quite old [`{revtex4-1}` layout](http://www.lyx.org/trac/attachment/ticket/9038/revtex4-1.layout)  that may serve as a useful starting point, given the compatability between `{quantumarticle}` and `{revtex4-1}`.

**Comment by cgogolin** [comment]
A LyX version of the template would definitely be nice. Concerning basing it on revtex, I have my reservations. I deliberately based the `{quantumarticle}` on the article `{class}`. We want to stay good friends with the APS and so it shouldn't look like we are "stealing" their code.

**Comment by cgranade** [comment]
I'll start working on a LyX layout, then, as that should make it much easier for LyX to interact with `{quantumarticle}`.

**Comment by valbert4** [comment]
Thanks for picking this up! Note that there are some issues with revtex class regarding compatibility with other packages. E.g. http://tex.stackexchange.com/questions/227385/inserting-a-pdf-file-in-revtex-4-1-with-reprint-option. Also I had a problem with their bib class file not doing what it said it would do http://tex.stackexchange.com/questions/252733/physical-review-x-phys-rev-x-prx-bibliography-style

**Comment by cgogolin** [comment]
Any news on the Lyx layout? I would like to release version 2.0 in the next two weeks and it would be nice to have the Lyx layout in.

**Comment by cgogolin** [comment]
I have recently merged the lyx layout provided @ComradeVVA into `develop`.

@cgranade, could you try to use it and see if you encounter any problems?
