### ISSUE TITLE
\itshape in references

### ISSUE THREAD

**Issue by lschalleck** [cgogolin/quantum-journal#103]
Upon fetching 1903.10526v3 in Wordpress, for some reason all references included \itshape in the journal brackets right before the journal name resulting in being displayed as such in the preview. Removed it manually for now.

**Comment by cgogolin** [comment]
Thanks for reporting but this is the wrong github project :-) 

I have implemented a fix here https://github.com/quantum-journal/o3po/pull/136 an will merge it in the coming weeks.

**Comment by lschalleck** [comment]
Oh, hoops, I guess I just spotted the new issue button and thought yeah that's it :)
