### ISSUE TITLE
Fix cr/lf in CTAN submission scrip

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#105]
I think git convert cl/lf depending on the platform the repository is checked out on. It would thus be best to make sure the packaging scrip produces files complient with CTAN rules: https://ctan.org/file/help/ctan/CTAN-upload-addendum#crlf

**Comment by cgogolin** [comment]
Now that v6.0 has been released it would be great if @johannesjmeyer could upload the new version to CTAN and maybe also address this issue? Thanks a lot in advance!

**Comment by johannesjmeyer** [comment]
CTAN submission is prepared using a tool by cgranade which in turn uses the builtin compress factility of Windows, which, according to CTAN, is a "good zip program". This means we can close this issue.
