### ISSUE TITLE
Iftoggle{@xstring is not correctly working my template - That I'm compiling on Overleaf.com

### ISSUE THREAD

**Issue by ravian-salman** [cgogolin/quantum-journal#109]
Please compile this file and you will see the error messages. The quantumjournal cls file has a lot of errors

[QuantumScience Journal (1).zip](https://github.com/quantum-journal/quantum-journal/files/3980373/QuantumScience.Journal.1.zip)
`

**Comment by cgogolin** [comment]
Thanks for submitting this bug and apologies for the delay in answering. We will give it a look soon.

**Comment by cgogolin** [comment]
I just had a quick look. The source you submitted compiles perfectly well after resolving the following problem:

* quantumarticle (like most article type document classes) does not have a `\subsubsection` command. You can use `\paragraph` instead.
* You use the macro `\expval`, which however ist not defined in your source file. Is there any document class that defines `\expval`? If so we can maybe add support to quantumarticle.
* In line 263 you have a double underscore in your equation, which is not valid in LaTeX.
* You have a few `\\` at the beginning of some of your theorems and at other places in your source file and LaTeX rightfully complains that there is no line to end at this point.
* in lines 384, 390, and 391 you have a double underscores, which is invalid in LaTeX.
* In line 419 you have a `&`, which is a control character in LaTeX. If you want a & in your output you should use `\&`. This appears in a few more cases.
* In line 434 you have a `\newline` after a `\section` which is not valid LaTeX
* In line 454 you have a `^` which must not appear in normal text, You probably want to enclose the part in $ $ to switch to math mode. 
* In line 729 you have `\gama`, which does not exist, you probably meant `\gamma`

After fixing these errors the file compiles normally.

Non of the above issues are a consequence of using `quantumarticle` but simply a consequence of not using LaTeX properly.
