### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by maxtremblay** [cgogolin/quantum-journal#119]
Hello,

Just to warn you that I get the following warning when I run the notebook without any modification.
It affects only the _Colormesh_ and _Multiple Plots_

**System informations:**
- Notebook server version: 6.1.5
- Python 3.9.0 
- IPython 7.19.0 
- Matplotlib 3.3.3
- Backend: pgf

**The warning:**
```bash
MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  
Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  
This will become an error two minor releases later.
plt.pcolormesh(X, Y, Z, cmap = 'viridis')
```

**Comment by johannesjmeyer** [comment]
I was just passing by to make a new issue and saw that one. I now ported the logic in the notebook to a separate package that you find here: https://github.com/johannesjmeyer/rsmf. Your problem was probably solved in the mean time, but maybe it is useful for the future :)

**Comment by maxtremblay** [comment]
Hey, my problem was solved since then, but thanks for the link. I will definitely look at that for a future article :smile:
