### ISSUE TITLE
Remove quantum-plots

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#121]
I ported the logic of the quantum-plots notebook to a separate package, rsmf ("right-size my figures") that you find here: https://github.com/johannesjmeyer/rsmf

As this is better maintained, also works with revtex and less prone to errors I would suggest we remove quantum-plots from this repo and link to the new package instead. If you are not comfortable with advertising third party packages in the example document then we can surely figure something out!

**Comment by cgogolin** [comment]
Proposed solution sounds great to me. No need to duplicate code or fork. Can you make a PR that implements this, please?


On April 28, 2021 2:04:17 PM GMT+02:00, Johannes Jakob Meyer ***@***.***> wrote:
>I ported the logic of the quantum-plots notebook to a separate package, rsmf ("right-size my figures") that you find here: https://github.com/johannesjmeyer/rsmf
>
>As this is better maintained, also works with revtex and less prone to errors I would suggest we remove quantum-plots from this repo and link to the new package instead. If you are not comfortable with advertising third party packages in the example document then we can surely figure something out!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/issues/121
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
Will do. Afterwards we can bump the version number!
