### ISSUE TITLE
Add default bibstyle

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#122]
In separate discussions, the idea of creating a default bibstyle for Quantum came up (on GitHub mostly in #120). The idea is to provide a basic style that authors can use if they wish to and that provides as much convenience as we can reasonably put in there, e.g. for checking of DOIs, etc.

The discussions yielded the following ideas, which are not set in stone, though:
- One could base the bibstyle on existing ones, e.g. from Aram: https://github.com/harrow/arxiv-bibstyle
- Here is a resource about adding DOI linking: https://www.math.tamu.edu/~comech/tools/bibtex-doi-eprint/; https://github.com/harrow/arxiv-bibstyle/blob/master/plainnat-eprint.bst
- Author lists should be given in full with first names spelled out as a metter of inclusivity
- We should put volume and page, but issue number is anachronistic
- We should support as many non-standard entry types beyond @article and @book as possible
- DOI, eprint and url links should be there
- If possible, we could check if DOIs are given conditional on some environment variables (`@unpublished` etc.) so that the check only runs for submission-ready entries (no idea how to do that though)

**Comment by dwierichs** [comment]
Happy to work on this! :)

**Comment by dwierichs** [comment]
Given the amount of options one has to print out the bibitems, some more design choices would be good to have. I could come up with some, but presumably it's worth it to discuss them (at least to some extent) beforehand.
Some aspects would be: 
1. Sorting order of the entries,
2. Formatting of journal name, volume and page numbers,
3. Whether to print only the starting page,
4. Are the typically supported entry types sufficient? (table wrapping from p.14 to p.15 in [here](http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf) )

**Comment by johannesjmeyer** [comment]
I think it would be good to base it on the apsrev style which is kind of a de-facto standard. One theme should be that we try to avoid shortening stuff because space is free on the internet, so I would put all the pages we have. I imagine something along the following lines (not so sure about the italics for the title though):

[7] Jacob Biamonte, Peter Wittek, Nicola Pancotti, Patrick Rebentrost, Nathan Wiebe and Seth Lloyd. _Quantum machine learning._ Nature **549**, 195–202 (2017). DOI: [10.1038/nature23474](https://doi.org/10.1038/nature23474). eprint: [arXiv:1611.09347](https://www.arxiv.org/abs/1611.09347).

Ordered by appearance in the text. Concerning the supported types, I don't know if there is one for websites and code repositories? That would be nice.

But I think we should gather some more input first, @cgogolin? What do you personally think @dwierichs?

**Comment by dwierichs** [comment]
That sounds good! I like the formatting in the example. In particular I think the separating effect of the italic title between authors and journal name is pretty helpful for readers to scan references quickly.
I read this in the template, just to make sure: We only ever want DOI if published, eprint and never give the publisher website directly, correct? (In particular @cgogolin knows this, I presume?) 
Regarding the ordering I agree that by appearance is most convenient.
I will make sure there is a website and a repository entry type.

**Comment by johannesjmeyer** [comment]
> I read this in the template, just to make sure: We only ever want DOI if published, eprint and never give the publisher website directly, correct? (In particular @cgogolin knows this, I presume?)

Yes, always DOI, never website (just because DOIs are guaranteed to remain stable even if the publisher restructures their website). But I don't know if you can extract the information if this is published or not via biblatex (but I guess yes, because it somehow also detects what kind of documentclass you use). Eprint if available (technically it is not necessary for open access, but figuring that out is surely too complicated).

> I will make sure there is a website and a repository entry type.

That would actually be quite a cool feature in general 🤔

**Comment by dwierichs** [comment]
Some preference questions:
1. Do you prefer
    [2] Ville Bergholm... [_Pennylane_](https://github.com/PennyLaneAI/pennylane) on github.com.
    [3] Johannes Jakob Meyer. [_right-size my figures_](https://github.com/johannesjmeyer/rsmf) on github.com.  
    or 
    [2] Ville Bergholm... _Pennylane_ on github.com. [Pennylane](https://github.com/PennyLaneAI/pennylane)
    [3] Johannes Jakob Meyer. _right-size my figures_ on github.com. [rsmf](https://github.com/johannesjmeyer/rsmf)
    or 
    [2] Ville Bergholm... [_Pennylane_](https://github.com/PennyLaneAI/pennylane) on github.com.
    [3] Johannes Jakob Meyer. _right-size my figures_ on github.com. [rsmf](https://github.com/johannesjmeyer/rsmf)
    i.e. have the title be the link, add an extra mention of the title/a short name/an acronym that forms the link or do the latter but only if there really is a second name/acronym.
2. For a reference that only has an eprint reference, the standalone year in brackets looks a bit weird to me, what do you think?
    [7] Jacob Biamonte, Peter Wittek, Nicola Pancotti, Patrick Rebentrost, Nathan Wiebe and Seth Lloyd. _Quantum machine learning_. (2016). eprint: [arXiv:1611.09347](https://www.arxiv.org/abs/1611.09347).

**Comment by johannesjmeyer** [comment]
I think the most applied use case for the repo would be to link code for simulations, because the big packages usually have associated publications you should cite instead. So for packages like PennyLane or rsmf I would tend towards something like

[2] Ville Bergholm, ...,. _PennyLane_. (2021) github: [pennylane/pennylane v0.15.0](https://github.com/PennyLaneAI/pennylane/tree/v0.15.0)

This notation would be similar to DOI and eprint in a sense. Not so sure about the version tags, but they are kind of required to make the year make sense.

But for repos the title makes less sense, see 

[2] Tom Hubregtsen, ..., Johannes Jakob Meyer. _qhack_. (2021) github: [thubregtsen/qhack](https://github.com/thubregtsen/qhack)

So maybe having it stripped down is a good idea, like

[2] Tom Hubregtsen, ..., Johannes Jakob Meyer. github: [thubregtsen/qhack](https://github.com/thubregtsen/qhack)

? These are also just suggestions, I think in the end we can converge to something everybody is happy with!

Concerning your other question, I think this is still okay, but I see that the place where the journal reference would be is a bit weird. Maybe

[7] Jacob Biamonte, Peter Wittek, Nicola Pancotti, Patrick Rebentrost, Nathan Wiebe and Seth Lloyd. Quantum machine learning. arXiv preprint (2016). eprint: arXiv:1611.09347.

?

**Comment by dwierichs** [comment]
I like the structure github: link, in particular because it follows the DOI/eprint structure as you said.

I was wondering about even processing the commit of the repo or the version of the package in bibtex.
But I think this can be taken care of by the user, i.e. if you really want to cite the package in a certain version, they should link a specific commit status and/or branch and include the version in the title (I also can include a version attribute, which is to only ever be passed by the user in this scenario if that is better, positioning-wise.) 
In the scenario where the user does not want to cite a specific version (the more common one, I believe), we don't need to print it. The year would just indicate the year of usage/access then.

Printing out the github handle makes it more important who owns the repo. I think usually this is a good thing and makes things clearer, but it is something one should discuss, in my opinion.

Regarding the eprint-only year display question, I came up with the very same solution, so I guess it has a preliminary majority vote :)

**Comment by dwierichs** [comment]
And considering packages that also have an article, wouldn't it be nice to combine those?

**Comment by cgogolin** [comment]
I think I would prefer to have the link written out. I know I am old-fashioned, but I like to "know" what I am clicking on. A caveat here is that outputting URLs in bibtex/latex can be non trivial due to special characters / escaping.

For eprints only I think the year can be omitted. It can be derived from the arxiv number. 

Putting the eprint after the year makes sens for entries that have a journal version and eprint because the eprint often predates the year of publication.

The journal name + volume + page can be a good text for the DOI link.

Im addition I would day: display eprint always, even if a doi or URL is given.

URL can be suppressed if either eprint or doi is present. Often auto generated bibfiles contain the link to publisher website and/or the arxiv in addition to a doi or eprint. Double links should be avoided.

**Comment by dwierichs** [comment]
I will check out the implementation of special characters/which ones might be relevant/dangerous in particular.
A second caveat of printing the full URL is that giving a version link of a repository will clutter the bibliography with a long string of numbers and letters. One could make an exception for this case, but that kind of defeats the purpose of putting "transparent" links, I think.

Yes, the eprint will basically always be displayed, and the DOI if existing. URL only ever will be printed if both, eprint and DOI are missing. With double links you mean having the DOI and the URL at the same time, right? This I agree would not be nice (and does not happen according to the previous rule).

Linking the DOI via the journal name + volume + pages is in conflict with printing transparent links and means that the DOI number is not visible to readers at all. I like the idea, though. Personally, I'd prefer to do this (I don't know whether people recognize papers by remembering the DOI, I don't) and to not rely on links being transparent at all cost.

**Comment by cgogolin** [comment]
Very good points. I think then I agree that hiding the github links and instead showing the DOIs is a good proposal. Thanks!

**Comment by dwierichs** [comment]
@cgogolin @johannesjmeyer  I created a PR: [#123](https://github.com/quantum-journal/quantum-journal/pull/123)

**Comment by cgogolin** [comment]
This will soon be addessed in #123  and #126
