### ISSUE TITLE
allow for affiliations with symbols

### ISSUE THREAD

**Issue by sinesha** [cgogolin/quantum-journal#134]
or alternatively for \thanks that appear near the affiliation. We tried to add a "these two authors contributed equally" note, and couldn't find a good implementation. see two attempts: 

1) with \affiliation 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/2291353/150628496-9f486f20-7a0b-4a62-ab3a-e23261888f50.png">

2) with \thanks 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/2291353/150628517-722439ea-4808-406f-b9eb-47e79dabcf45.png">

**Comment by cgogolin** [comment]
I strongly advise against misusing \affiliation for this as the content of this command is used to construct the meta-data of the publication.

-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by cgogolin** [comment]
As we are approaching a new release: What is wrong with using \thanks? It is a standard latex command also supported by many other styles and so should be fairly well known.

**Comment by cgogolin** [comment]
@sinesha What is wrong with using the standard \thanks command for this?

**Comment by cgogolin** [comment]
Closing this for now.
