### ISSUE TITLE
Enable verification that a work using the template has actually been published in Quantum

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#15]
It would be nice if the template would allow readers to easily verify that a given work typeset with it was actually published in Quantum.

The most reliable way to implement this would be based on the DOI of the work, but there is the following problem: The DOI will only be assigned once the final version is on the arXiv, so the final version on the arXiv cannot contain the DOI. 

An alternative and rather robust way would be the following:

The template could produce a button linking to `http://quantum-journal.org/?s=[title]`. On the current website this opens the search page with a search for the title of the paper.

Pro:
- no proble with circular dependency
- easy to implement

Con:
- future websites would need to support this interface
- the title might not be strictly unique

Any thoughts on this?

**Comment by sinesha** [comment]
Alternatively, the paper could generate its own DOI suffix (something unique, like an hash of the title). Once the final version is uploaded to the arXiv, we at Quantum can go there, find the DOI and register it.

**Comment by cgranade** [comment]
Is it possible for the Quantum DOI authority to issue DOIs based on the arXiv number? That would require each submission have at least two arXiv versions, since the arXiv number isn't known at the time of initial submission, but would result in something human readable and unique, at least.

**Comment by cgogolin** [comment]
We can decide on the DOI suffix ourselves. We can make up pretty much anything we want. Most importantly, any DOI must point to exactly one document, i.e., a specific version of the paper on the arXiv.

I am not sure it is a good idea to put the arXiv identifier into the DOI. The arXiv can change there identifier scheme in the future, we might decide at some point that Quantum should no longer be an arXiv overlay, the DOI should (if it should be at all human readable) refer to the publication date, rather than the arXiv date...

**Comment by cgogolin** [comment]
I finde the idea of the paper automatically generating its DOI (say from a hash of the title) very cool, however, it has one important caveat: Can we ensure that all future implementations will generate the same hash given a title? MD5 is standardized, but the representation of the title string could change? If this happens we will be stuck with dead links in the papers when the pdfs are regenerated by the arXiv with the new version of LaTeX. We would be more on the safe side, if the identification of the article would  be done my our website based on a search query, then we can later patch/change/improve this algorithm, without having to regenerate the pdfs.

**Comment by cgogolin** [comment]
I have implemented a "click the title searches for that title on quantum-journal.org" function in cc7ad4cd0155348d076118ae48364b5e4c6b8be1
