### ISSUE TITLE
Auto-link DOIs

### ISSUE THREAD

**Issue by rumschuettel** [cgogolin/quantum-journal#17]
It might be worth adding something like
```
\newbibmacro{string+doi}[1]{\iffieldundef{doi}{#1}{\href{https://dx.doi.org/\thefield{doi}}{#1}}}
\DeclareFieldFormat{title}{\usebibmacro{string+doi}{\mkbibemph{#1}}}
\DeclareFieldFormat[article]{title}{\usebibmacro{string+doi}{\mkbibquote{#1}}}
\DeclareFieldFormat[incollection]{title}{\usebibmacro{string+doi}{\mkbibquote{#1}}}
```
to auto-generate hyperlinks for doi's, saving the authors from doing this manually. This works with biblatex.

**Comment by cgogolin** [comment]
Thanks for the suggestion. We will look into this.

Unfortunately things are not as easy as they might seem at first sight:
- Detokenization can be an issue http://tex.stackexchange.com/questions/3802/how-to-get-doi-links-in-bibliography
- `biblatex` should not become a requirement for using `quantumarticle`, so the above code must only be executed if the authors did load biblatex
- Authors should still be able to use what ever bibliography style they want and at least some do automatically take care creating clickable links from the doi field.

**Comment by rumschuettel** [comment]
I agree to be more encompassing, so maybe it's worth writing this and similar commands depending on whether the user uses e.g. amsrefs or so.

I would go further and print visual hints at bibliography entries that do not have a doi assigned; that way you could also print a large blob of text at the top saying something like "did you check whether all the references have DOI's? If so, add doi=none to references that do not have any; note that you will not get assigned a DOI if a reference is missing a DOI."

As an author, I would definitely like to get such a visual reminder instead of accidentally forgetting one, and then not getting a DOI myself.

Just a suggestion :)

**Comment by cgranade** [comment]
I've used `{quantumarticle}` together with the `apsrev4-1.bst` BibTeX style file (not even BibLaTeX) to make bibliographies with linked DOIs, and it seems to work pretty well [[1610.00336](https://arxiv.org/abs/1610.00336)]. I agree that BibLaTeX support with linked DOIs would be a very nice thing to have, but I also agree with @cgogolin that BibLaTeX shouldn't be a requirement. Is it possible to tell programmatically, perhaps, whether BibLaTeX is in use or not? For instance, could we use an `\AtBeginDocument` command to check for BibLaTeX and conditionally include the bibmacros that you've suggested?

**Comment by cgogolin** [comment]
@cgranade Yes, you can check for whether a package was loaded or not: http://tex.stackexchange.com/questions/16199/test-if-a-package-or-package-option-is-loaded so we can in principle only execute these commands if BibLaTeX is loaded.

We should also think about which part of the citation should become the link. I would rather not make it the title, because people might decide to omit the title in their citation style. I would opt for the  journal, volume, issue, and page part to become the link.

Finally, with BibLaTeX we can even check if all citations that are an article and have the journal set, or are a book have a doi and throw a class warning if not. This would be really nice!

With all this I am still worried that we can potentially do something that messes up some bibliography styles. An thoughts or experience on that?

**Comment by cgogolin** [comment]
How shall we handle the case in which authors do not want to use BibLaTeX? For example, I just got an email of someone, who had generated a .bbl with BibTeX and the revtex class. Then changing to `quantumarticle` without re-running BibTeX obviously messes things up (this is not surprising currently). Revtex loads natbib by default and does all sorts of other things, which we don't do.

Maybe we should also load natbib by default if BibLaTeX is not used?

**Comment by cgogolin** [comment]
Loading natbib also seems to be sufficient to get DOI links ([see here](http://tex.stackexchange.com/questions/3802/how-to-get-doi-links-in-bibliography)).

Maybe we can just warn if neither `natbib` nor `biblatex`are loaded but a \bibliography command is used (that is citation formating is not done manually) and do something like the above if biblatex is loaded? That should guarantee full compatibility, but warn if no reasonable output can be expected?

**Comment by cgogolin** [comment]
I partially adress this in 7a73f6d.

**Comment by cgogolin** [comment]
I am closing this for now, as I think we have a pretty comprehensive description on how to achieve DOI links in the template and the documentclass already sets good default options for both natbib and biblatex (unfortunately the latter does not work well with the arXiv right now) and throws meaningful warnings that should point authors in the right direction in case they do not use either of the two.
