### ISSUE TITLE
Add unit test 

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#19]
`quantumarticle` should have a set of [unit tests](https://en.wikipedia.org/wiki/Unit_testing) that just try to compile a bunch of real world papers from the arXiv with the class to check if any regressions have been introduced. I have never set-up a unit test framework, so help would be much appreciated.

**Comment by cgranade** [comment]
I've used Travis CI on a number of different projects before, such that I think it should be pretty straightforward to set up here as well. I'm less familiar with unit testing in LaTeX, but at the very least it should be possible to double-check that all existing examples compile without errors. That might give us a good starting point to build more formal unit testing on after that?

**Comment by cgogolin** [comment]
Sounds perfect. Travis CI sounds like a good solution.

**Comment by cgogolin** [comment]
Any news on this?

**Comment by cgranade** [comment]
Unfortunately, Travis hasn't moved on the package whitelist issue for ``latex-xcolor`` since November 10. Weirdly, though, they have mentioned that a commit from **2015** [may have fixed it](https://github.com/travis-ci/apt-package-whitelist/commit/3b1225e2)? I'll investigate more today, restarting the build to check.

**Comment by cgranade** [comment]
It seems as though there were some issues with package names that may now be resolved, so I'm back at work on #20, trying to get the unit test working with the container-based configuration.

**Comment by johannesjmeyer** [comment]
After googling around a bit, it seems that the least intrusive way to implement unit tests with latex is to use [the log file](https://tex.stackexchange.com/questions/12067/whats-the-folk-lore-on-automatic-testing-of-tex-programming). Output of pdftex can be made [more verbose](https://github.com/KaTeX/KaTeX/wiki/Examining-TeX) and can then be parsed.

**Comment by cgogolin** [comment]
We decided that it is hard to add unit test to this project that would actually add value.
