### ISSUE TITLE
\bibliographystyle{plainnat} breaks revtex4-1 compat

### ISSUE THREAD

**Issue by cgranade** [cgogolin/quantum-journal#28]
Currently, ``quantumarticle.cls`` defines the following ``{revtex4-1}`` compatability logic:

```
\ifrevtexcompatibility
...
\AtEndPreamble{%
  \@ifpackageloaded{biblatex}{}{%
    \usepackage[numbers,sort&compress]{natbib}
    \bibliographystyle{plainnat}
    ...
  }
}
\fi
```

If using this with the ``{revtex4-1}``-compatible ``\bibliographystyle{apsrev4-1}`` command, however, BibTeX complains with the following error message:

```
Illegal, another \bibstyle command---line 59 of file document.aux
 : \bibstyle
 :          {apsrev4-1}
I'm skipping whatever remains of this command
```

Since this tends to get buried in LaTeX build output, the user-visible effects are mainly that the bibliography fails to render. I would suggest that either ``{quantumarticle}`` allow for the use of other ``\bibliographystyle`` arguments, or that the class raises a more explicit error to the effect that other bibliography styles are disallowed.

**Comment by cgogolin** [comment]
Can you check whether my proposed fix works for you? It is a bit more involved. The idea is to patch `\bibliographystyle` and `\bibliography` such that the former records whether it has been called before and the latter executes `\bibliographystile{plainnat}` only if no other style was set by the user before.
This allows the use of other styles in revtex compatibility mode, but also retains full compatibility with revtex, which does not require you to set a style at all.

**Comment by cgranade** [comment]
I think that works as a solution, yeah. I'll take a look at implementing that, then, hopefully using #20 to check correctness.

**Comment by cgranade** [comment]
Ah, I missed that you had pushed c22ee9061ad22ae69887473837bd2cb79cf29109, but I just tested that and it works great with alternate bibstyles now. Thank you for all the help!

**Comment by cgogolin** [comment]
Somehow my "solution" however produces an error when you are not running in revtex compatibility mode, which I don't understand, because the code that redefines the \bibliography macro should never be execute in this case...

**Comment by cgogolin** [comment]
I can no longer reproduce the problem I described in my last comment and otherwise the issue seems to be fixed.
