### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by marozols** [cgogolin/quantum-journal#30]
I don't know if quantumarticle is supposed to be used only with the original font, but when I tried to set a different font (by adding `\usepackage{mathpazo}` in the preamble), I noticed that this does not affect environments (such as `proof`, `theorem`, etc.) as well as footnotes.  I assume this is not intentional (it seems more like a bug than a feature to me).

Another minor comment: why is the footnote symbol in italic?  Is it so that one doesn't confuse `$x$\footnote{...}` with `$x^2$`?

**Comment by cgogolin** [comment]
To guarantee a uniform look and feel,  authors are indeed not supposed to load any packages that change the used fonts. There is however no general technical restriction in place that prevents this.

The behavior you describe thus sounds strange and I will look into it when I have time.

The font of the footnote symbol is different from the math font to avoid confusion.

**Comment by cgogolin** [comment]
I am closing this issue for now as loading of font packages has been disabled altogether.
