### ISSUE TITLE
HTTP vs HTTPS for generated hyperlinks

### ISSUE THREAD

**Issue by cgranade** [cgogolin/quantum-journal#31]
Currently, ``{quantumarticle}`` generates plain HTTP (not HTTPS links) to the following domains:

- ``quantum-journal.org``
- ``orcid.org``
- ``dx.doi.org``

Both ``orcid.org`` and ``dx.doi.org``, however, support HTTPS such that specifying non-secure links is not needed. For general security, I'd suggest upgrading the URLs generated for these domains to HTTPS versions.

**Comment by cgogolin** [comment]
Our own domain quantumarticle.org does not support https currently (this will change in the future).

Can you implement the change and submit a pull request against the 'develop' branch?

**Comment by cgranade** [comment]
Sounds good, mainly wanted to check before starting the PR. Will get that in ASAP, then.
