### ISSUE TITLE
CTAN submission?

### ISSUE THREAD

**Issue by cgranade** [cgogolin/quantum-journal#33]
Is it worthwhile to submit to CTAN? It seems as though MiKTeX in particular picks up CTAN packages for automatic installation on Windows, so that might make things easier for MiKTeX users. If it's of interest, I've been working on automatic CTAN archive building functionality in the [cgranade/posh-tex](https://github.com/cgranade/posh-tex) package, though it is still admittedly experimental.

**Comment by cgogolin** [comment]
Yes, that would be great! Now that the code base has stabilized a bit it does make sense to prepare for inclusion into CTAN.

**Comment by cgranade** [comment]
Sounds good, then. The CTAN submission package should probably include ``quantumarticle.cls``, ``quantum-template.pdf``, ``quantum-template.tex``, ``README.md``, ``install.ps1`` and ``install.sh``, I would guess? That is, all but the git metadata. Given that this is a pretty straightforward package, I think CTAN would likely prefer we submit as a simple archive, without the full ``quantumarticle.tds.zip`` [that sorts everything according to the TeX Directory Structure](http://dante.ctan.org/tds-guidelines.html). This is pretty easy to do manually, via [ctanify](https://www.ctan.org/pkg/ctanify?lang=en), or on platforms without Perl, by posh-tex. I'm happy to make a PR with a new build script for either of these three strategies. Any particular thoughts? Thanks!

**Comment by cgogolin** [comment]
You are the expert, so please go ahead! Sounds great and thanks for the work!

**Comment by cgranade** [comment]
No worries, happy to help! Anyway, with #35 merged in, it should be straightforward to upload to CTAN at the next release tag.

**Comment by cgogolin** [comment]
The just released version 3.0 is the first that I imagine could be worth uploading to CTAN. Let's let it sit there for a couple of days to see whether any problems pop up and then prepare a submission?

**Comment by cgranade** [comment]
Agreed, I think that makes a lot of sense.

**Comment by johannesjmeyer** [comment]
I had a look on what has to go into a CTAN submission for a class file, and while most of them use the `.dtx` format I have found some that don't. For example [this documentclass](https://ctan.org/tex-archive/macros/latex/contrib/elegantpaper). 

This means we can just write a documentation of the documentclass and package it up. This means the following files are needed:

- `README.md`
- `quantumarticle.cls`
- `quantum-template.tex`
- `quantum-template.pdf`
- `quantumarticle.tex` _(to be created)_
- `quantumarticle.pdf` _(to be created)_
- `License` _(to be copied)_

As far as I understand the matter we can omit the install scripts. What do you think @cgranade? You are the only person here that has some experience. 

If this is okay, writing a short script that just packages those files into a .zip should be a piece of cake.

**Comment by cgranade** [comment]
Sorry for the delay! I've written a script already to generate CTAN submission zip files that may be of interest; it's what I use to [submit `{revquantum}` to CTAN](https://github.com/cgranade/revquantum/blob/master/Install.ps1#L19), for instance.
The following snippet builds revquantum's documentation from the DocStrip (`*.dtx`) file, as well as the style file itself, then packages that into a ZIP file for sending to CTAN. 

```powershell
param(
    [switch] $CTAN
)

#region Bootstrap PoShTeX
if (!(Get-Module -ListAvailable -Name posh-tex -ErrorAction SilentlyContinue)) {
    Install-Module posh-tex -Scope CurrentUser
}
Import-Module posh-tex
#endregion

Out-TeXStyle revquantum
Out-TeXStyleDocumentation revquantum

Install-TeXUserResource tex/latex/revquantum revquantum.sty, revquantum.pdf

Install-PandocUserResource templates pandoc/templates/revquantum.latex -ErrorAction Continue

if ($CTAN) {
    Invoke-TeXBuildEngine example.tex
    Export-CTANArchive -ArchiveLayout Simple revquantum.ins, README.md, example.tex, example.pdf, Install.ps1
}
```

I've not tested with building a class file rather than a style file, but I imagine it should go more or less the same way. If you'd like, I'm happy to take a stab at making such a script for `{quantumarticle}` as well.

**Comment by johannesjmeyer** [comment]
I'd rather refrain from having a `.dtx` file and simply zip up the files I listed above to make the CTAN package (which should be a oneliner I think) [see also #90]. I'm in the process of writing a short documentation of the document class for that purpose.

**Comment by cgranade** [comment]
Fair enough. To be clear, the script I posted above need not use a `*.dtx`; rather, that's the process that I used on `{revquantum}`. The `Out-TeXStyle revquantum` and `Out-TeXStyleDocumentation revquantum` produce the `*.sty` and `*.pdf` that are included by the `Export-CTANArchive` command below.

**Comment by cgogolin** [comment]
What is holding us back from submitting to CTAN?

**Comment by johannesjmeyer** [comment]
Actually nothing. I intended to wait for some time until the new release has settled in, but I got distracted from it due to outside circumstances and just forgot. Thanks for bringing it back up!

**Comment by johannesjmeyer** [comment]
Just submitted to CTAN, I'll keep you posted when it is online.

**Comment by cgogolin** [comment]
Excellent. Thanks!
