### ISSUE TITLE
Class option to produce articles without the Quantum journal styling

### ISSUE THREAD

**Issue by dbranford** [cgogolin/quantum-journal#37]
The class should feature a draft/preprint/unpublished key (possibly active by default) which could disable features such as

 - Use of the quantum logo
 - Use of the quantum colour scheme
 - Hyperlinking the title to a search of quantum-journal.org (this could resovle https://github.com/quantum-journal/quantum-journal/issues/29)
 - Alternative format for `\maketitle`

which would produce an article which does not look like it is associated with any particular journal, similar to the distinction between formatting of `revtex` and final published versions in Physical Review.

Submitting an article with one class when the final article should be produced (by the authors) with a different class can be inconvenient, risking incompatibilities between classes which authors may wish to avoid.  Similarly, authors wishing to use features permitted by `quantumarticle` may find themselves unable to use other classes like `revtex` to produce a submission version of their article, yet starting from a basic class like `article` is likely to be deemed an excessive amount of work pushing authors again towards using `quantumarticle` for submissions.

This feature request would enable authors to produce articles for submission which would use `quantumarticle` as the document class and all its features to prepare articles for submission to the Quantum journal without the PDF produced needing to look like an article published in Quantum, while allowing articles to be converted to adopt the house style upon acceptance with minimal risk of complications.

**Comment by cgogolin** [comment]
With 16089e5 I have added an `unpublished` option that disables all Quantum branding but leave the document geometry unchanged. More precisely it
1. It disables the `accepted=` option and hence suppresses the appearance of the Quantum logo (but the command \Quantum is still defined and available) 
2. It disables the quantum colour scheme in the sense that the title, page numbers, and hyperref links appear in the normal text color. The color quantumviolet is still defined and available unchanged to the user.
3. The title does no longer hyperlink to a search page on quantum-journal.org (I think this resolves #29)

I have decided against implementing an alternative looking format for `\maketitle` as I don't want to annoy authors with changing the document geometry in any way. When they switch this option off for the final version nothing should "move around" in the document in a unintended way.

**Comment by cgogolin** [comment]
We can discuss whether the `unpublished` option should add a note such as "Unpublished manuscript" in the footline of each page similar, but so to say inverse, to what the `accepted=` option does. Any thoughts on this?

**Comment by dbranford** [comment]
An "Unpublished manuscript" note would fit well with the idea of distinguishing these articles from published quantum articles, but changes made in https://github.com/quantum-journal/quantum-journal/commit/16089e5dfb1ee4759ebdc2d75b0294d19b362c45 have already distinguished the visual style.

A piece of text explicitly declaring the manuscript unpublished may be undesirable to users wishing to use `quantumarticle` (with the `unpublished` option) to submit accepted versions of manuscripts which have been accepted to other journals - this is probably not an audience to worry about being accommodating too much.
Unpublished could constitute a reference to private/not to be publicly distributed version, as such it may be viewed as an inappropriate comment to be placed upon arXiv submissions.

To me such a note would likely discourage use of the `unpublished` option, but may also discourage use of `quantumarticle` for articles not accepted in the journal/submitted elsewhere.  I'd suggest it would be better to encourage use of `unpublished` and not add such a note.

**Comment by cgogolin** [comment]
Ok, I basically share this view. Then we leave things as they are and I close this for now.

**Comment by sopalab** [comment]
Hi, while I personally have a relatively strong distaste for the preprint option it definitely has its merits. Most importantly it gives the older collaborators the possibility to view things better because of larger spacing and font size. So somehow I would love to see it enabled in some way.
