### ISSUE TITLE
Accepted YYYY-MM-DD looks funny in single page documents 

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#40]
I don't know why but the Quantum logo in the  "Accepted in Quantum  YYYY-MM-DD..." mark in the footline looks funny in documents with just one single page. I suspect a bug or problem with `fancyhdr`.

**Comment by dbranford** [comment]
Do you have an example for this?  I don't notice anything, possibly https://github.com/quantum-journal/quantum-journal/commit/3ecd0b2f0e411bdd798d4d926df5845f40b7d5fa has removed this problem.

**Comment by cgogolin** [comment]
The following was my minimal (non) working example
```
\documentclass[accepted=2017-05-09]{quantumarticle}
\begin{document}
\title{Hello}
\date{\today}
\author{A. Foo}
\begin{abstract}
  foo
\end{abstract}
\maketitle
\end{document}
```
but the savebox trick indeed seems to have solved this. Great!
