### ISSUE TITLE
Color package produces an error when we pass on unknown options

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#41]
We pass on unknown options to `color` and `xcolor` to make a solution suggested by LaTeX for option clashes actually work. For `xcolor` this works great but `color` throws an error for unknown options.

**Comment by cgogolin** [comment]
Some background: This was discovered by Mark Pearce as we errornously also passed on the `accepted=` option to color. Here is why:

We load `xcolor` (which is essentailly color plus some extra functionality) in the documentclass to define the Quantum violet. Some people however like to load the `color` or `xcolor` packages of themselves (for example because they are moving over to quantumarticle.cls from a class that doesn't load any color package). If they provide options to the package, LaTeX throws the following error (because `xcolor` was already loaded by `quantumarticle.cls`):
```
ERROR: LaTeX Error: Option clash for package color.
```
LaTeX further suggests to add the options to color to the `\documentclass` command so that they are passed on when the documentclass loads color. Passing on of options to `color` or `xcolor`, however doesn't work automatically. So we pass all unknown options on to `color` and `xcolor` to make this fix proposed by LaTeX actually work by including the following the quantumarticle.cls:
```
\DeclareOption*{
   \PassOptionsToPackage{\CurrentOption}{color}
   \PassOptionsToPackage{\CurrentOption}{xcolor}
}
```
`xcolor` simply ignores options it doesn't know about, but `color` complains with the error spotted by Mark Pearce. The problem is that the `accepted=` option was, contrary to other options, declared with `xkeyval`  and is therefore treated as "unknown" by the DeclareOption* macro.

**Comment by cgogolin** [comment]
To completely resolve this we should: 1) completely switch over to xkeyval 2) only pass options to color that it actually understands.

**Comment by dbranford** [comment]
I'm not sure I see why `\DeclareOption*{<processing>}` was introduced like this, `color` (and `xcolor`) can use options from the global list eg

```
\documentclass[usenames,dvipsnames]{article}
\usepackage{color}

\begin{document}
\textcolor{RubineRed}{Foo}
\end{document}
```

and all this processing of package options doesn't fix the issues of users loading `color`/`xcolor` with conflicting options in the document (which should be documented, pointing users to manually utilise `\PassOptionsToPackage` if  necessary).  Is there an example for which the `\DeclareOption*{<processing>}` code you have was needed?

**Comment by cgogolin** [comment]
Very good point! The reason is as follows: In a previous version, adding `\usepackage[some_option]{xcolor}` to a document would make LaTeX throw the error
```
ERROR: LaTeX Error: Option clash for package xcolor.
```
and offer the following help text:
```
The package xcolor has already been loaded with options:
  []
There has now been an attempt to load it with options
  [some_option]
Adding the global options:
  ,some_option
to your \documentclass declaration may fix this.
```
And this supposed "fix" simply didn't do anything because the respective option was just ignored.

Now, after double checking, I can no longer reproduce this error with the current version and this makes sense because we are loading `xcolor` only if it has not already been loaded via 
```
\AtBeginDocument{
  [...]
  \@ifpackageloaded{xcolor}{}{\RequirePackage{xcolor}}
  [...]
}
```
which, as far as I can tell, is the right thing to do.

Now, what surprises me is that not only the error is gone but that, even without the code that explicitly passes on the options, `color` is now able to pick up global options such as `monochrome` given in `\documentclass`. This definitely didn't work before I switched option processing over to `xkeyval`.

So, all in all it looks like we can get ride entirely of this ugly bit of code!

**Comment by cgogolin** [comment]
I just pushed a change that removes the `\DeclareOption*{<processing>}` bit. All my tests run fine, can you confirm that this is working?

**Comment by dbranford** [comment]
Looks to work fine to me.

` \@ifpackageloaded{xcolor}{}{\RequirePackage{xcolor}}` doesn't seem to be different to `\RequirePackage{xcolor}` as the latter does nothing if the package is already loaded, the crucial thing to avoid option clashes when we load the package without any options is to place the `\RequirePackage{xcolor}` as late as possible (which is done with the `\AtBeginDocument`), `xstring` and `tikz` also seem to similarly load with this longer line.

**Comment by cgogolin** [comment]
Thanks! Yes, indeed this check seems superfluous. I have removed in in 7d56dc9.
