### ISSUE TITLE
\Quantum is undefined if tikz is not installed

### ISSUE THREAD

**Issue by dbranford** [cgogolin/quantum-journal#42]
The conditional loading of TikZ (https://github.com/quantum-journal/quantum-journal/blob/3dbc0d8bc6639308a4c9aa0eae3739b1d97c7742/quantumarticle.cls#L1062-L1072) means that `\Quantum` becomes undefined if `tikz.sty` is not present on the users system.  This can manifest itself in less than obvious ways

```latex
\documentclass[accepted=2017-05-09]{quantumarticle}
\makeatletter
\@tikzfalse
\makeatother

\begin{document}
Foo
\end{document}
```

Potentially a PDF of the Quantum logo should be packaged with the class file (if this class is on CTAN as per https://github.com/quantum-journal/quantum-journal/issues/33 then including the graphic in a bundle should be feasible and would add no complications for users with an up-to-date installation). As far as I can tell this could facilitate removal of `tikz` from the class entirely, otherwise `tikz` should probably be an explicit dependency of `quantumarticle` unless doing something like

````latex
\if@tikz [...] \else\newcommand\Quantum{Quantum}\fi
````

 is acceptable.

**Comment by cgogolin** [comment]
Well spotted!
In the long run, I agree that a PDF of the logo can be included. As long as we are still in a phase of rapid development I would like keep the installation process for people as easy as possible and keep everything in one `.cls` file. Actually, we might want to keep things like this for as long as `quantumarticle.cls` is not officially supported by the arXiv and authors still need to manually upload the document class alongside their submission when uploading...

At the same time, as the logo is just branding, I would rather not code a hard dependence on tikz into `quantumarticle.cls`, hence I would go for the suggested fallback for the Quantum logo.

**Comment by cgogolin** [comment]
I am closing this for now as getting rid of tikz and including a PDF is something to think about again in a rather distant future...
