### ISSUE TITLE
Recommend IEEEeqnarray

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#51]
Erik W wrote:

You could consider recommending IEEEeqnarray instead of or in addition to align for aligned equations, especially for the more complicated cases. It's an environment that lets you do aligned equations but it gives you complete control over the number and alignment of columns. It's already included in the LaTeX systems on ArXiv as well as (at least) APS and IOP. There's a good introduction to it starting in section 4 here: [](http://moser-isi.ethz.ch/docs/typeset_equations.pdf). Recent versions of "The Not So Short Introduction to LaTeX2\varepsilon" also recommend it.

In case you're not familiar with it I've attached a chain of equations from some recent notes I created using a combination of IEEEeqnarray and IEEEeqnarraybox.
![pr1-278](https://user-images.githubusercontent.com/6409421/43365286-d16b13e4-932a-11e8-8edd-8883c647bce4.png)
Notice that, among other things, the fourth and sixth lines are exactly aligned just inside the opening brackets on the lines directly preceding them.

**Comment by johannesjmeyer** [comment]
One could just write a short paragraph in the quantum-template.tex recommending IEEEeqnarray.

**Comment by cgogolin** [comment]
Fixed in #72
