### ISSUE TITLE
Remind people not to use `\today`

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#52]
Erik W. wrote:

Since it's an ArXiv overlay, it's probably a good place to remind people not to use `\date{\today}` in ArXiv papers but instead put in explicitly the date of submission (not announcement). See https://arxiv.org/help/faq/today, as well as https://arxiv.org/abs/quant-ph/0003004 for an example of a famous paper that is currently showing a date wrong by 8 years because of this.

**Comment by cgogolin** [comment]
The solution should be to redefine \today to throw an error that explains that using \today is a very bad idea for papers on the arXiv but also says that there is a class options, i.e., `allowtoday` that disabled the re-definition of \today and restores the standard behavior.

**Comment by johannesjmeyer** [comment]
This should also be fixed by now @cgogolin.
