### ISSUE TITLE
Support for wide figures

### ISSUE THREAD

**Issue by pyramids** [cgogolin/quantum-journal#56]
I would welcome support for the `figure*` environment to be able to draw quantum circuits that are wider than a single column in the `twocolumn` mode.

**Comment by cgogolin** [comment]
This is a very good suggestion. As of lately I have concentrated on upgrading the website of Quantum, but will look into this when I have more time to spare again for improving the documentclass. Thanks for reporting!

**Comment by johannesjmeyer** [comment]
Maybe we can just ask the authors of [this beautiful paper](https://quantum-journal.org/papers/q-2019-02-04-119/) how they did it, cause they have a wide figure in their paper.

@cgogolin could you do that?

**Comment by cgogolin** [comment]
They actually used `figure*` and it works flawlessly, also, e.g., in the `quatum-template.tex` file.

**Comment by cgogolin** [comment]
I have added a comment that this works in #71. Closing.
