### ISSUE TITLE
Bad output due to bitmapped fonts beeing used with some versions of TexLive

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#6]
Reported by Mateus Araújo:

quantumarticle produces horrible output on some computers.

It is trivial to fix it, however, you only need to add \usepackage{lmodern} to the preamble
If you want to know what is going on, see here: http://tex.stackexchange.com/questions/1291/why-are-bitmap-fonts-used-automatically

In a nuthsell you ask for T1 fonts, whereas the default Computer Modern fonts are OT1, and TexLive replaces it with some bitmapped fonts.
\usepackage{lmodern} tells it to use the font Latin Modern instead, which is a proper T1 version of Computer Modern, with support for diacritics.

**Comment by cgogolin** [comment]
Looks like we should check for either {lmodern} or {cm-super} being installed and throw a warning if neither of them is available.

**Comment by araujoms** [comment]
This happened with the TeXLive 2015 that is installed by default in Ubuntu 16.04.

While installing the font cm-super solves the problem, I think the proper solution is to use the font Latin Modern, see here: http://tex.stackexchange.com/questions/1390/latin-modern-vs-cm-super

**Comment by cgogolin** [comment]
I could verify the problem by uninstalling {cm-super}, which I usually have installed on my machine. Yes, I agree that we should default to {lmodern}, but if {lmodern} is not installed, I think, we should check for {cm-super} and if that is also not available output a warning. I don't have time to implement this today, but will look into it.

**Comment by araujoms** [comment]
Isn't it easier to simply refuse to compile if the package `lmodern` is not available? It is not as if it is difficult to install it. I would actually bet that it is installed by default in all TeX distributions.

**Comment by cgogolin** [comment]
I thought the same was true for {cm-super} :-)

**Comment by araujoms** [comment]
Oh. Indeed. But the problem is that if cm-super is not installed you don't get a warning, you just get bad output, and I had to investigate what was going on. 

On the other hand, to use Latin Modern you need to include `\usepackage{lmodern}` in the preamble, so if you don't have it compilation fails and you get a very clear error message.

**Comment by cgogolin** [comment]
I am marking this as closed. I hope you like the solution. Thanks for reporting and the discussion!

**Comment by araujoms** [comment]
I'm confused. I tested your solution, and it works fine when I have Latin Modern installed. However, if I remove Latin Modern to use the fallback cm-super it refuses to compile with the message "File `cm-super.sty` not found", even though I have cm-super installed. And there is no problem with my cm-super installation, as the old version of the Quantum template compiles fine using it.

**Comment by cgogolin** [comment]
Memo to self: If you know you don't have the time to implement and test a fix, don't try it :-). 

The new fix should work. type1ec.sty is part of the cm-super package: https://www.ctan.org/pkg/type1ec?lang=en

**Comment by araujoms** [comment]
Yep, now it works perfectly! I hope I'm not the only Linux user that will benefit from this change =)

**Comment by cgogolin** [comment]
Thanks again!
