### ISSUE TITLE
Make paragraph headings sans-serif and increase title spacing

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#60]
Paragraph headings are right now typeset in serif font. I propose to set them in sans-serif instead to be consistent with the other headings that are also sans-serif.

Furthermore, the title currently has no spacing, this means that for long titles will not look good if a capital letter on the lower line collides with a g,y,j etc. on the upper line.

**Comment by cgogolin** [comment]
The paragraph headings are much more part of the body text, because they are on the same line as the first line of the paragraph they are starting. I think, sans serif and serif fonts are essentially never mixed in typography in the same paragraph/line. I would thus prefer to keep `\paragraph` on the normal body font and keep setting it apart solely by making it bold.

**Comment by johannesjmeyer** [comment]
This makes total sense! What do you think about the vertical title spacing?

**Comment by cgogolin** [comment]
Yes, that should be changed. Can you make a PR with a space that you think looks reasonable?

**Comment by johannesjmeyer** [comment]
Yes, I can do this after I finished testing the refacored class file. Do you have an idea of how to do it? I looked it up online but this seems to be less trivial than I expected.

**Comment by cgogolin** [comment]
Do you mean an idea for how to test or an idea for who to add the space?

**Comment by johannesjmeyer** [comment]
Adding the space.

**Comment by cgogolin** [comment]
It is actually surprising that there is no space in the first place, no? It must be a consequence of the hackery we have in `\@titleatfontsize` to prevent authors from using certain macros in the title...

**Comment by johannesjmeyer** [comment]
Yes, that's true. I will dive into this and have a detailed look. But it is really suprising because I'd expect the spacing to be the default (which should be something like 1,25 or so?).

**Comment by cgogolin** [comment]
Turns out, all one has to do is move the "#1" outside the `\begingroup....\endgroup`. I don't fully understand what is happening here, but I suppose the linespread is somehow not set when the font size is changed in side a group. See #64
