### ISSUE TITLE
Remove @compatibility statements?

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#63]
As the `@compatibility` statements only serve as a vehicle of [compatibility with LaTeX 2.09](https://tex.stackexchange.com/questions/31838/whats-the-use-of-the-compatibility-condition), should we remove them? This was an issue 20 years ago, when LaTeX 2e replaced LaTeX 2.09, but nowadays it is not. Has anyone tried to typeset a quantumarticle document with LaTeX 2.09?

**Comment by cgogolin** [comment]
They were inherited from `article`, on which `quantumarticle` is based. It is probably safe to remove them.

**Comment by cgogolin** [comment]
As this will be deal with as part of #65 I am closing this.
