### ISSUE TITLE
Link breaking in onecolumn mode fails

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#66]
![link-breaking-issue](https://user-images.githubusercontent.com/46889760/52236561-77802300-28c7-11e9-8d71-4bde3429024e.PNG)

Link breaking does not work as expected in single-column mode.

**Comment by cgogolin** [comment]
I don't think this is specific to single column mode but a more general problem of hyperref under certain compilers, see also here: https://tex.stackexchange.com/questions/50490/hyperref-package-breaklinks-option Which LaTeX variant did you use for this example?

**Comment by johannesjmeyer** [comment]
I used PdfLaTeX and the weird thing is that link breaking works if `twocolumn` is selected, but not if `onecolumn` is selected.

**Comment by cgogolin** [comment]
Does the same happen in the plain vanilla article class?

I cannot test, as there is no minimal non-working example... 

On 3 March 2019 12:14:57 CET, johannesjmeyer <notifications@github.com> wrote:
>I used PdfLaTeX and the weird thing is that link breaking works if
>`twocolumn` is selected, but not if `onecolumn` is selected. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/issues/66#issuecomment-469012661

-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by johannesjmeyer** [comment]
Sorry, here it is!

[quantum-template-linkbreak.zip](https://github.com/quantum-journal/quantum-journal/files/2927701/quantum-template-linkbreak.zip)

Renders as this pdf on my machine: [quantum-template-linkbreak.pdf](https://github.com/quantum-journal/quantum-journal/files/2927702/quantum-template-linkbreak.pdf)

**Comment by johannesjmeyer** [comment]
Ok, I believe it is due to the 11pt option. I can't reproduce it if I remove it.

**Comment by cgogolin** [comment]
I can reproduce the problem also with 12pt, 10pt and without giving a pt option. You just have to hadd/remove words until LaTeX has the link in a sufficiently "inconvenient" location. The same however also happens with the plain vanilla `article` class. I think this is a problem of hyperref and I don't think we can do much about it.
I am closing this. Feel free to re-open in case you disagree.
