### ISSUE TITLE
Weird section spacing - possbile due to wideequation

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#68]
![section_beforeskip](https://user-images.githubusercontent.com/46889760/52263605-de392700-292f-11e9-9c26-13295f50405e.PNG)

The spacing is completely eaten up (reproducible with the quantum template when titlepage is activated). A possible reason could be the wideequation that latex wants to put onto the page. Maybe there is some kind of penalty on this that we could increase.

**Comment by johannesjmeyer** [comment]
I can confirm that the beforeskip works like a charm if the wide equation is on the next page.

**Comment by cgogolin** [comment]
I remember that we discussed this but lost track of the status of this issue. Do we have a fix?

**Comment by johannesjmeyer** [comment]
Not yet.

**Comment by johannesjmeyer** [comment]
Here is a minimal non-working example of the issue:
[quantum-template-sectionspacing.pdf](https://github.com/quantum-journal/quantum-journal/files/2945644/quantum-template-sectionspacing.pdf)
[quantum-template-sectionspacing.zip](https://github.com/quantum-journal/quantum-journal/files/2945645/quantum-template-sectionspacing.zip)

**Comment by cgogolin** [comment]
So then what was the deal about `beforeskip`? You said above that it works like a charm, but I don't understand what that exactly means :-)

**Comment by johannesjmeyer** [comment]
The thing is that the beforeskip of the section is not working when a `widetext` environment is present on the same page as the section break (as in the image above). If the `widetext` is on the next page, the section spacing is correct.

**Comment by cgogolin** [comment]
Thanks for investigating!

It is funny how it screws up the spacing of the _first_ section in the column before the wide equation, and not that of the section immediately preceding the wide equation...

Anyway, I can reproduce the very same behavior with `revtex4-1` (just take your example, change the documentclass and comment the `\twocolumn` command). I thus think this is a bug in `ltxgrid` and we can't do much about it...
