### ISSUE TITLE
What is the point of passing breaklinks to hyperref for pdf output?

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#76]
In the document class `breaklinks` is passed to `hyperref` if we output a pdf

```latex
\ifnumequal{\pdfoutput}{0}
    {}
    {\PassOptionsToPackage{breaklinks=true}{hyperref}}
```

I had a look into the `hyperref` manual and there it says that it would determine automatically if it should break links or not. Is this code necessary?

**Comment by cgogolin** [comment]
I don't remember the details, but it is related to a limitation/bug(?) of `hyperref`, that prevents it from breaking links when the DVI driver is in use. This option is added to at least make `hyperref` [admit](https://latex.org/forum/viewtopic.php?t=17716) that it doesn't work properly.

**Comment by johannesjmeyer** [comment]
Okay, then this is all good.
