### ISSUE TITLE
Manuscritps that do not call \date at all seem to trigger the avoid \today error

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#77]
This is a problem, obviously, as the error message doesn't make any sense in this case.

**Comment by cgogolin** [comment]
I think the problem is that if `\date` is not called, then LaTeX automatically populates `\@date` via `\today`. I am not entirely sure how to solve this, because simply not calling `\@date` in the class, is not enough to not trigger the error.

**Comment by johannesjmeyer** [comment]
Fixed by #79
