### ISSUE TITLE
Compatibility of quantumplots with old versions of matplotlib

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#82]
Quantum plots throws an error if used with old versions of jupyter / matplotlib due to `mpl.use()` being called.

**Comment by cgogolin** [comment]
I consider this a "bug", but think we can leave it open and release the current version. We have clearly marked this as a beta feature and users will probably discover more glitches.

**Comment by cgogolin** [comment]
I think we can safely close this issue. This will only happen with versions of matplotlib that are now _very_ old.
