### ISSUE TITLE
Write a script that packages the necessary files for CTAN submission

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#90]

**Comment by johannesjmeyer** [comment]
There was already a solution to this in `install.ps1` when the parameter `-CTAN` was given. This solution works well on my machine. I just had to change the files that were included in the package.

**Comment by cgogolin** [comment]
@johannesjmeyer could you please resubmit the just released v5.1 to CTAN?

**Comment by johannesjmeyer** [comment]
Done, pending confirmation by the CTAN administrators. See also the small PR I opened where I just updated some lone version tags.

**Comment by cgogolin** [comment]
Excellent. Thanks! 

On 3 November 2020 11:56:38 CET, Johannes Jakob Meyer <notifications@github.com> wrote:
>Done, pending confirmation by the CTAN administrators. See also the small PR I opened where I just updated some lone version tags.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/quantum-journal/quantum-journal/issues/90#issuecomment-721045040
-- 
Christian Gogolin
http://www.cgogolin.de
