### ISSUE TITLE
Should fleqn work or not?

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#91]
The option `fleqn` (flush equations left) is actually defined twice in the document class, once as 
```latex
\DeclareOptionX{fleqn}{\input{fleqn.clo}}
```
and some lines below as dummy option 
```latex
\DeclareOptionX{fleqn}{}
```

Right now, the option does not work if provided, but if the second dummy option would be removed it would work as expected. 

The question is: what is the desired behaviour?

**Comment by cgogolin** [comment]
Wow, how did you find that? Yes, I think it is a bug that was introduced when the dummy options for compatibility were added.

**Comment by johannesjmeyer** [comment]
I was starting to document `quantumarticle` and I recognized the duplicate option. Is it okay if I just remove the second (dummy) option and commit this directly against develop?

**Comment by cgogolin** [comment]
Yes, please do that. Thanks!
