### ISSUE TITLE
Superscriptaddress option in template is a dummy

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#94]
I just realized that the option `superscriptaddress` which is used in `quantum-template.tex` is actually a dummy. We should either remove it (from the template) or implement a new feature that fills it with life (in the class file).

**Comment by cgogolin** [comment]
If users give an option that is not defined, LaTeX throws an error. The dummy options are there to prevent this from happening when users convert from a different document class. To make our promise, that converting is really just as easy as replacing the document class, true. 

Superscript addresses is the default with quantumarticle.cls, so I think it is ok if that option doesn't do anything.

**Comment by johannesjmeyer** [comment]
This is not what concerns me. It is the fact that the option is passed to quantumarticle in the quantum-template.tex. I think we should not include options in the template that do nothing – the user could think that the option changes the default behavior.
________________________________

**Comment by cgogolin** [comment]
Ah! You have a point there. I guess the original reason for this was that the template should look similar if one compiles it with `quantumacrticle` replaced by `revtex4-1`, but maybe you are right and we should not set that option. I don't have a strong opinion. You decide.

**Comment by johannesjmeyer** [comment]
Okay, I see. But I would remove it because quantumarticle should make a coherent package on its own.
________________________________

**Comment by cgogolin** [comment]
Ok, then feel free to do so.
