### ISSUE TITLE
Pre-release checks

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#98]
I have pushed various smaller changes to the readme, the documentation, the template, ... into `develop` in preparation of the upcoming release of v5.0. @johannesjmeyer as you asked whether you could help with anything: Could you give everything a last look, see if it makes all sense structurally, check that I haven't forgotten any major improvement in the change log, and change anything you think might be worth changing (or do any subset of that you have the time for)? Thank you very much in advance! We are very much on the final stretch here!

**Comment by cgogolin** [comment]
One comment: Most links will only start working once we have merged into `master`, so don't check for broken links yet.

**Comment by johannesjmeyer** [comment]
I'm on it, you'll get a PR tomorrow.
